### PR TITLE
Translation of the Story folder to Polish

### PR DESCRIPTION
**Pull request by GitUser14975**

### CODE REVIEW

**Comment by Pattrigue** [comment]
Hi, thank you for the pull request. Please ensure that the json files do not contain errors - currently, three of them contain errors (see the LintJSON action details).
image

In addition, please create separate, smaller pull requests with fewer files to make it more manageable and easier to read through, review and merge (the TownNPCs should not be part of the same pull request as the story dialogue).
Good work so far, though!

**Review by Pattrigue — CHANGES_REQUESTED** [review]
Please split this pull request into multiple separate pull requests. I cannot review and merge this pull request when you keep adding more and more changes.

**Comment by GitUser14975** [comment]
> Please split this pull request into multiple separate pull requests. I cannot review and merge this pull request when you keep adding more and more changes.

Hi, I'm sorry for the late reply. I haven't noticed your earlier message. Also, how can I split the pull request to separate requests? I haven't worked on github before and I'm not sure how it works. Once again I apologize for the problem.

**Comment by Pattrigue** [comment]
> > Please split this pull request into multiple separate pull requests. I cannot review and merge this pull request when you keep adding more and more changes.
> 
> Hi, I'm sorry for the late reply. I haven't noticed your earlier message. Also, how can I split the pull request to separate requests? I haven't worked on github before and I'm not sure how it works. Once again I apologize for the problem.

No problem, let me try and explain it.
You need to create a new branch for each pull request.
The best way is to make a new branch for each folder (i.e. a branch for each NPC).

To fix this pull request, simply revert all the files from the TownNPC folder so that they are the same as the ones here in this repository. Store your changed files somewhere locally, on your machine, so those won't be lost.
Then, create a new branch for one of the NPCs you've made dialogue for, and replace the files on that branch with the files you stored locally for that NPC - and then make a pull request.
Do this for each NPC.

Does that make sense?

**Comment by GitUser14975** [comment]
> 

Yes, I think I understand now. Thank you!

**Pull request closed without merging**
